## Exercise on manipulating `timeseries_dataset_from_array` and `window` functions

In [1]:
import tensorflow as tf
import keras
import numpy as np

In [2]:
# Some artificial univariate time series data
data = np.arange(0,100)

1. Use `keras.utils.timeseries_dataset_from_array` to
* chop the data into 10 non-overlapping windows of length 10
* the resulting dataset should contain individual items

```
[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
...
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************
```

In [3]:
ds1 = keras.utils.timeseries_dataset_from_array(
    data,
    targets=None,
    sequence_length=10,
    sequence_stride=10,
    batch_size=None
)

2025-11-13 12:05:51.303874: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-11-13 12:05:51.303902: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-11-13 12:05:51.303908: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-11-13 12:05:51.303927: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-11-13 12:05:51.303942: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
for item in ds1:
    print(f"{item} {item.shape}")
    print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] (10,)
**************************************************
[50 51 52 53 54 55 56 57 58 59] (10,)
**************************************************
[60 61 62 63 64 65 66 67 68 69] (10,)
**************************************************
[70 71 72 73 74 75 76 77 78 79] (10,)
**************************************************
[80 81 82 83 84 85 86 87 88 89] (10,)
**************************************************
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************


2025-11-13 12:05:55.713295: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Same exercise using `window`.   
Start with `tf.data.Dataset.range(100)`

In [5]:
ds1_window = (
    tf.data.Dataset.range(100)
    .window(size=10,)
    .flat_map(lambda ds : ds.batch(10)))

In [6]:
for item in ds1_window:
    print(f"{item} {item.shape}")
    print("*"*50)

[0 1 2 3 4 5 6 7 8 9] (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] (10,)
**************************************************
[50 51 52 53 54 55 56 57 58 59] (10,)
**************************************************
[60 61 62 63 64 65 66 67 68 69] (10,)
**************************************************
[70 71 72 73 74 75 76 77 78 79] (10,)
**************************************************
[80 81 82 83 84 85 86 87 88 89] (10,)
**************************************************
[90 91 92 93 94 95 96 97 98 99] (10,)
**************************************************


2025-11-13 12:07:04.663574: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


2. Use `keras.utils.timeseries_dataset_from_array` to
* chop the data into 10 non-overlapping windows of length 10
* the resulting dataset should contain batches of three elements
```
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
...
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************
```

In [7]:
ds2 = keras.utils.timeseries_dataset_from_array(
    data,
    targets=None,
    sequence_length=10,
    sequence_stride=10,
    batch_size=3
)

In [8]:
for item in ds2:
    print(f"{item} {item.shape}")
    print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************


2025-11-13 12:08:58.824449: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Same exercise using `window`.   
Start with `tf.data.Dataset.range(100)`

In [ ]:

#! ds2_window = pass
ds2_window = (
    tf.data.Dataset.range(100)
    .window(size=10,)
    .flat_map(lambda ds : ds.batch(10))).batch(3)

In [15]:
for item in ds2_window:
    print(f"{item} {item.shape}")
    print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************


2025-11-13 12:10:27.492802: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


3. Use `keras.utils.timeseries_dataset_from_array` to
* chop the data into windows of length 10
* consecutive windows should have 5 elements in common (should overlap by 5 elements)
* the resulting dataset should contain batches of three elements
```
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
...
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
**************************************************
```

In [16]:

#! ds3 = pass
ds3 = keras.utils.timeseries_dataset_from_array(
    data,
    targets=None,
    sequence_length=10,
    #? Vijf gelijke items
    sequence_stride=5,
    batch_size=3
)

In [17]:
for item in ds3:
    print(f"{item} {item.shape}")
    print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************
[[45 46 47 48 49 50 51 52 53 54]
 [50 51 52 53 54 55 56 57 58 59]
 [55 56 57 58 59 60 61 62 63 64]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [65 66 67 68 69 70 71 72 73 74]
 [70 71 72 73 74 75 76 77 78 79]] (3, 10)
**************************************************
[[75 76 77 78 79 80 81 82 83 84]
 [80 81 82 83 84 85 86 87 88 89]
 [85 86 87 88 89 90 91 92 93 94]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
****

2025-11-13 12:12:00.474819: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Same exercise using `window`.   
Start with `tf.data.Dataset.range(100)`

In [ ]:

#! ds3_window = pass
ds3_window = (
    tf.data.Dataset.range(100)
    #? shift = 5 + drop_remainder = True
    .window(size=10, shift=5, drop_remainder=True)
    .flat_map(lambda ds : ds.batch(10))
    .batch(3))

In [96]:
for item in ds3_window:
    print(f"{item} {item.shape}")
    print("*"*50)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]] (3, 10)
**************************************************
[[15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]
 [25 26 27 28 29 30 31 32 33 34]] (3, 10)
**************************************************
[[30 31 32 33 34 35 36 37 38 39]
 [35 36 37 38 39 40 41 42 43 44]
 [40 41 42 43 44 45 46 47 48 49]] (3, 10)
**************************************************
[[45 46 47 48 49 50 51 52 53 54]
 [50 51 52 53 54 55 56 57 58 59]
 [55 56 57 58 59 60 61 62 63 64]] (3, 10)
**************************************************
[[60 61 62 63 64 65 66 67 68 69]
 [65 66 67 68 69 70 71 72 73 74]
 [70 71 72 73 74 75 76 77 78 79]] (3, 10)
**************************************************
[[75 76 77 78 79 80 81 82 83 84]
 [80 81 82 83 84 85 86 87 88 89]
 [85 86 87 88 89 90 91 92 93 94]] (3, 10)
**************************************************
[[90 91 92 93 94 95 96 97 98 99]] (1, 10)
****

2025-11-13 12:28:39.284336: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


4. Use `keras.utils.timeseries_dataset_from_array` to
* chop the data into windows of length 10
* consecutive windows should have 5 elements in common
* the target for each window is the element immediately following this window
* no batching is required
```
0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
...
[85 86 87 88 89 90 91 92 93 94] maps to 95 and has shape (10,)
**************************************************
```

In [29]:
ds4 = keras.utils.timeseries_dataset_from_array(
    data,
    #? the target for each window is the element immediately following this window
    targets=data[10:],
    sequence_length=10,
    #? Vijf gelijke items
    sequence_stride=5,
    #? no batching is required
    batch_size=None
)

In [30]:
for item, label in ds4:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************
[15 16 17 18 19 20 21 22 23 24] maps to 25 and has shape (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] maps to 30 and has shape (10,)
**************************************************
[25 26 27 28 29 30 31 32 33 34] maps to 35 and has shape (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] maps to 40 and has shape (10,)
**************************************************
[35 36 37 38 39 40 41 42 43 44] maps to 45 and has shape (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] maps to 50 and has shape (10,)
***********************************

2025-11-13 12:17:12.237377: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Same exercise using `window`.   
Start with `tf.data.Dataset.range(100)`

In [59]:
ds4_window = (
    tf.data.Dataset.range(100)
    #? size = 11
    .window(size=11, shift=5, drop_remainder=True)
    #? ds.batch(11)
    .flat_map(lambda ds : ds.batch(11))
    .map(lambda window: (window[:-1], window[-1])))

In [60]:
for item, label in ds4_window:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[0 1 2 3 4 5 6 7 8 9] maps to 10 and has shape (10,)
**************************************************
[ 5  6  7  8  9 10 11 12 13 14] maps to 15 and has shape (10,)
**************************************************
[10 11 12 13 14 15 16 17 18 19] maps to 20 and has shape (10,)
**************************************************
[15 16 17 18 19 20 21 22 23 24] maps to 25 and has shape (10,)
**************************************************
[20 21 22 23 24 25 26 27 28 29] maps to 30 and has shape (10,)
**************************************************
[25 26 27 28 29 30 31 32 33 34] maps to 35 and has shape (10,)
**************************************************
[30 31 32 33 34 35 36 37 38 39] maps to 40 and has shape (10,)
**************************************************
[35 36 37 38 39 40 41 42 43 44] maps to 45 and has shape (10,)
**************************************************
[40 41 42 43 44 45 46 47 48 49] maps to 50 and has shape (10,)
***********************************

2025-11-13 12:21:45.507466: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


5. Try to "predict" multiple values in one go
* Map sequences of length 5 to a single sequence of length 2 that contains the next two elements.
* Sequences should overlap by 4 elements
* No batching
* Solve using "window".
* Start with windows of length 7.

* Thus:
    * Inputs: windows of length 5
    * Targets: windows of length 2  
    * E.g.:
        * [0,1,2,3,4] -> [5,6]  
        * [1,2,3,4,5] -> [6,7]

```
[0 1 2 3 4] maps to [5 6] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [6 7] and has shape (5,)
**************************************************
...
[93 94 95 96 97] maps to [98 99] and has shape (5,)
**************************************************
```



In [90]:
#! ds5_window = pass

ds5_window =  (
    tf.data.Dataset.range(100)
    #? size = 7 en 4 overlappen
    .window(size=7, shift=1, drop_remainder=True)
    #? ds.batch(7)
    .flat_map(lambda ds : ds.batch(7))
    .map(lambda window: (window[:-2], window[-2:])))

In [91]:
for item, label in ds5_window:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[0 1 2 3 4] maps to [5 6] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [6 7] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [7 8] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [8 9] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [ 9 10] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [10 11] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [11 12] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [12 13] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [13 14] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [14 15] and has shape (5,)
**************************************************
[10 11 1

2025-11-13 12:27:56.514218: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


6. Add shuffling (buffer_size = 10_000 and seed=42) and batching (batches of size 10) to the previous exercise
```
[[52 53 54 55 56]
 [24 25 26 27 28]
 [75 76 77 78 79]
 [30 31 32 33 34]
 [ 0  1  2  3  4]
 [65 66 67 68 69]
 [38 39 40 41 42]
 [51 52 53 54 55]
 [62 63 64 65 66]
 [21 22 23 24 25]] maps to [[57 58]
 [29 30]
 [80 81]
 [35 36]
 [ 5  6]
 [70 71]
 [43 44]
 [56 57]
 [67 68]
 [26 27]] and has shape (10, 5)
**************************************************
...
[[26 27 28 29 30]
 [40 41 42 43 44]
 [28 29 30 31 32]
 [35 36 37 38 39]] maps to [[31 32]
 [45 46]
 [33 34]
 [40 41]] and has shape (4, 5)
**************************************************
```

In [ ]:

#!
ds6_window =  (
    tf.data.Dataset.range(100)
    #? size = 7 en 4 overlappen
    .window(size=7, shift=1, drop_remainder=True)
    #? ds.batch(7)
    .flat_map(lambda ds : ds.batch(7))
    .map(lambda window: (window[:-2], window[-2:]))
    .shuffle(buffer_size=10000, seed=42)
    .batch(10))

In [98]:
for item, label in ds6_window:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[[15 16 17 18 19]
 [72 73 74 75 76]
 [10 11 12 13 14]
 [67 68 69 70 71]
 [ 3  4  5  6  7]
 [56 57 58 59 60]
 [46 47 48 49 50]
 [77 78 79 80 81]
 [76 77 78 79 80]
 [49 50 51 52 53]] maps to [[20 21]
 [77 78]
 [15 16]
 [72 73]
 [ 8  9]
 [61 62]
 [51 52]
 [82 83]
 [81 82]
 [54 55]] and has shape (10, 5)
**************************************************
[[54 55 56 57 58]
 [63 64 65 66 67]
 [19 20 21 22 23]
 [ 5  6  7  8  9]
 [12 13 14 15 16]
 [33 34 35 36 37]
 [71 72 73 74 75]
 [87 88 89 90 91]
 [14 15 16 17 18]
 [48 49 50 51 52]] maps to [[59 60]
 [68 69]
 [24 25]
 [10 11]
 [17 18]
 [38 39]
 [76 77]
 [92 93]
 [19 20]
 [53 54]] and has shape (10, 5)
**************************************************
[[20 21 22 23 24]
 [89 90 91 92 93]
 [42 43 44 45 46]
 [17 18 19 20 21]
 [32 33 34 35 36]
 [58 59 60 61 62]
 [68 69 70 71 72]
 [59 60 61 62 63]
 [93 94 95 96 97]
 [91 92 93 94 95]] maps to [[25 26]
 [94 95]
 [47 48]
 [22 23]
 [37 38]
 [63 64]
 [73 74]
 [64 65]
 [98 99]
 [96 97]] and has shape 

2025-11-13 12:29:09.376473: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


7. Create data for a simple sequence to sequence model.
* The input sequence should be of length 5
* The output should be a sequence of the same length, but containing the values one step into the future.  
Thus when the input sequence is $[0,1,2,3,4]$, the target sequence is $[1,2,3,4,5]$
* The input sequences should overlap by 4 elements.
* No batching

```
[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
...
[94 95 96 97 98] maps to [95 96 97 98 99] and has shape (5,)
**************************************************
```



In [111]:
#!
ds7_window = (
    tf.data.Dataset.range(100)
    #? size = 7 en 4 overlappen
    .window(size=6, shift=1, drop_remainder=True)
    #? ds.batch(7)
    .flat_map(lambda ds : ds.batch(7))
    .map(lambda window: (window[:-1], window[1:])))

In [112]:
for item, label in ds7_window:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[0 1 2 3 4] maps to [1 2 3 4 5] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [2 3 4 5 6] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [3 4 5 6 7] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [4 5 6 7 8] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [5 6 7 8 9] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [ 6  7  8  9 10] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [ 7  8  9 10 11] and has shape (5,)
**************************************************
[ 7  8  9 10 11] maps to [ 8  9 10 11 12] and has shape (5,)
**************************************************
[ 8  9 10 11 12] maps to [ 9 10 11 12 13] and has shape (5,)
**************************************************
[ 9 10 11 12 13] maps to [10 11 12 13 14] and h

2025-11-13 12:31:34.883420: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


8. Build training data for a more involved sequence to sequence model. At each step, the desired output consists of the next 3 elements.
* Input sequences of length 5
* Targets: sequences of length 5, where each sequence element consist of the next 3 data points.  
Thus when the input sequence is $[0,1,2,3,4]$, the target sequence is  
$[[1,2,3], \\\\
[2,3,4], \\\\
[3,4,5], \\\\
[4,5,6], \\\\
[5,6,7]]$
* No batching
```
[0 1 2 3 4] maps to [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]] and has shape (5,)
**************************************************
...
[92 93 94 95 96] maps to [[93 94 95]
 [94 95 96]
 [95 96 97]
 [96 97 98]
 [97 98 99]] and has shape (5,)
**************************************************
```


In [ ]:

#! Dit is super moeilijk schijnt
ds8_window = (tf.data.Dataset.range(100).window(
    size=1 + 3,
    shift=1,
    drop_remainder=True)
  .flat_map(lambda ds : ds.batch(1 + 3))
  .window(
      size=5,
      shift=1,
      drop_remainder=True)
  .flat_map(lambda ds: ds.batch(5))
  .map(lambda S : (S[:,0], S[:,1:]))
)

In [114]:
for item, label in ds8_window:
    print(f"{item} maps to {label} and has shape {item.shape}")
    print("*"*50)

[0 1 2 3 4] maps to [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]] and has shape (5,)
**************************************************
[1 2 3 4 5] maps to [[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]] and has shape (5,)
**************************************************
[2 3 4 5 6] maps to [[3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]] and has shape (5,)
**************************************************
[3 4 5 6 7] maps to [[ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]] and has shape (5,)
**************************************************
[4 5 6 7 8] maps to [[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]] and has shape (5,)
**************************************************
[5 6 7 8 9] maps to [[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]] and has shape (5,)
**************************************************
[ 6  7  8  9 10] maps to [[ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]] and has shape (5,)
**********************************

2025-11-13 12:31:57.286658: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
