# Einops programmeeroefeningen

[Einops tutorial, part 1: basics](https://einops.rocks/1-einops-basics/)

In [198]:
import einops
import numpy as np
import keras
import pandas

## 1.  Warmup exercises
Use einops to write a Python function to
### 1. Compute the inner product of two vectors

In [199]:
#? inner product =  inwendig product

x = keras.ops.arange(5)
y = keras.ops.arange(1,6)

x,y

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>)

In [200]:
val = einops.einsum(x, y, "i,i -> ")
val

<tf.Tensor: shape=(), dtype=int32, numpy=40>

### 2. Transpose a matrix.

In [201]:

#? Begin vector
x = keras.ops.arange(4)
#? Omvormen naar een matrix (2, 2)
x = keras.ops.reshape(x,newshape=(2,2))
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [202]:

#? Transponeren
y = einops.rearrange(x, "i j ->j i")
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 2],
       [1, 3]], dtype=int32)>

### 3. Compute the sum of each column of a matrix.
- Result is a vector with the same number of elements as the numberof columns

Matrix X:

|   | 0 | 1 | 2 |
|---|---|---|---|
| 0 | 0 | 1 | 2 |
| 1 | 3 | 4 | 5 |
| 2 | 6 | 7 | 8 |

In [203]:

#? Begin vector
x = keras.ops.arange(9)
#? Omvormen naar een matrix (3, 3)
x = keras.ops.reshape(x,newshape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

Resultaat:

| i |	Sum |
|--|--------|
| 0	| 3     |
|1	|12     |
|2	| 21    |

voor elke rij:
- Rij 0: 0 + 1 + 2 = 3
- Rij 1: 3 + 4 + 5 = 12
- Rij 2: 6 + 7 + 8 = 21

In [204]:
einops.einsum(x, ("i j -> i"))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3, 12, 21], dtype=int32)>

### 4. Compute $`AA^T`$ for a matrix $`A`$

In [205]:

#? Begin vector
x = keras.ops.arange(9)
#? Omvormen naar een matrix (3, 3)
x = keras.ops.reshape(x,newshape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [206]:

#? Transponeren
x_t = einops.rearrange(x, "i j ->j i")
x_t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [207]:

#! OF
x_t = keras.ops.transpose(x)

x_t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [208]:

#! Zonder einsum
y = keras.ops.matmul(x,x_t)
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]], dtype=int32)>

In [209]:

#! Met einsum en transponderen wordt direct gedaan tijdens de einsum
y = einops.einsum(x,x,"i k,j k -> i j")
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]], dtype=int32)>

### 5. Compute the trace of a (square) matrix.
- The trace is the sum of the diagonal elements of a matrix.

### 6. Compute the Hadamard product of two matrices.
- The Hadamard product is the element-wise product of two matrices

## 2  Exercises on rearrange and reduce
### 1. Create the following tensor using only `keras.ops.arange` and `einops.rearrange`: 

```python
[[3, 4],
[5, 6], 
[7, 8]] 
```

In [210]:

#? keras.ops.arange
x = keras.ops.arange(3, 9)
y = keras.ops.reshape(x,newshape=(3,2))
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [211]:

#? einops.rearrange
x = keras.ops.arange(3, 9)
y = einops.rearrange(x, "(x y) -> x y", x=3, y=2)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

- `(x y)` means: the 1-D axis is made of `x * y` items
- -> `x y` reshapes it into a 2-D tensor

### 2. Create the following tensor using only `keras.ops.arange` and `einops.rearrange`

```python
[[1, 2, 3],
[4, 5, 6]]
```

In [212]:

#? keras.ops.arange
x = keras.ops.arange(1,7)
print("x: "+ str(x))
y = keras.ops.reshape(x,newshape=(2,3))
y

x: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [213]:

#? einops.rearrange
x = keras.ops.arange(1,7)
einops.rearrange(x, "(x y) ->  x y", x=2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### 3. Create the following tensor using only `keras.ops.arange`and `einops.rearrange`:
```python
[[[1], [2], [3], [4], [5], [6]]]
```

In [214]:

#? keras.ops.arange
x = keras.ops.arange(1,7)
print("x: "+ str(x))
y = keras.ops.reshape(x, (1, 6, 1))
y

x: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


<tf.Tensor: shape=(1, 6, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]], dtype=int32)>

In [215]:

#? einops.rearrange
x = keras.ops.arange(1,7)
einops.rearrange(x, "x ->  1 x 1")

<tf.Tensor: shape=(1, 6, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]], dtype=int32)>

het patroon `"x -> 1 x 1"` betekent:
- neem de bestaande lengte `x` (dus 6)
- maak er een tensor van met vorm `(1, x, 1)`
→ dus `(1, 6, 1)`

### 4. Given a 1D tensor of temperatures, whose length will be a multiple of 7 and the first 7 days are for the first week, second 7 days for the secondweek, etc.

[meteo API](https://historical-forecast-api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&start_date=2025-11-04&end_date=2025-11-18&daily=temperature_2m_max&timezone=Europe%2FBerlin)

In [216]:
import requests
import pandas as pd

url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
    "latitude": 52.52,
    "longitude": 13.41,
    "start_date": "2025-10-04",
    "end_date": "2025-11-18",
    "daily": "temperature_2m_max",
    "timezone": "Europe/Berlin"
}

resp = requests.get(url, params=params)
data = resp.json()

# haal de data uit
dates = data["daily"]["time"]
temps = data["daily"]["temperature_2m_max"]

df = pd.DataFrame({"date": dates, "temp_max_C": temps})
print(temps)
print()
temps = np.array(temps)
days = len(temps)
weeks = days//7
weeks = temps[:weeks*7].reshape(weeks,7) #? vorm: (weken, 7 dagen)

print(weeks)

[12.9, 13.9, 15.8, 14.9, 15.8, 14.5, 15.1, 16.3, 14.3, 14.9, 13.1, 14.0, 13.7, 13.1, 10.7, 11.1, 13.8, 16.8, 15.3, 15.5, 12.4, 12.6, 9.9, 9.9, 11.2, 14.1, 12.3, 12.4, 15.7, 13.3, 12.3, 15.1, 15.8, 15.0, 12.9, 8.1, 8.4, 10.5, 10.5, 12.2, 15.5, 12.4, 7.2, 9.9, 6.1, 6.1]

[[12.9 13.9 15.8 14.9 15.8 14.5 15.1]
 [16.3 14.3 14.9 13.1 14.  13.7 13.1]
 [10.7 11.1 13.8 16.8 15.3 15.5 12.4]
 [12.6  9.9  9.9 11.2 14.1 12.3 12.4]
 [15.7 13.3 12.3 15.1 15.8 15.  12.9]
 [ 8.1  8.4 10.5 10.5 12.2 15.5 12.4]]


a. Compute the average temperature for each week given a 1D tensor of temperatures. Use only `einops` operations

In [220]:
avg_weeks = einops.reduce(weeks, "week day ->  week", "mean")
avg_weeks

array([14.7       , 14.2       , 13.65714286, 11.77142857, 14.3       ,
       11.08571429])

uitleg:
- "w d -> w" zegt: reduce de dagen-as d en laat alleen de week-as over
- "mean" neemt het gemiddelde over die dagen

b. For each day, subtract the average for the week the day belongs to. Use only `einops` operations.

c. Normalize the temperatures as follows: for each day, subtract theweekly average and divide by the weekly standard deviation. Use einops operations. Pass keras.ops.std to reduce.