In [9]:
%pip install numpy
%pip install einops
%pip install pillow

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
  Using cached pillow-12.0.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.8 kB)
Using cached pillow-12.0.0-cp312-cp312-macosx_11_0_arm64.whl (4.7 MB)
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
import einops

A = np.arange(12).reshape(3,4)  # 3x4 matrix
B = np.arange(-4,4).reshape(4,2)  # 4x2 matrix

# Met einops.einsum
C = einops.einsum(A, B, "i k,k j->i j")
print("Einops C: \n" + str(C))
# Zelfde resultaat met loops
C = np.empty((3,2))
for i in range(3):
    for j in range(2):
        total = 0
        for k in range(4):
            total += A[i, k] * B[k, j]
        C[i, j] = total

print("Loops C: \n" + str(C))


Einops C: 
[[  4  10]
 [-12  10]
 [-28  10]]
Loops C: 
[[  4.  10.]
 [-12.  10.]
 [-28.  10.]]


In [ ]:
A = np.arange(3)  # [0,1,2]
B = np.arange(1,3)  # [1,2]

C = einops.einsum(A, B, "i,j->i j")
print("Einops C: \n" + str(C))


C = np.empty(shape=(3,2))
for i in range(3): # First outer loop
	for j in range(1,2,1): # Second outer loop
		total= 0
		total+= A[i] * B[j] # No inner loop

	C[i,j] = total

print("Loops C: \n" + str(C))


Einops C: 
[[0 0]
 [1 2]
 [2 4]]
Loops C: 
[[  4.   0.]
 [-12.   2.]
 [-28.   4.]]
